ogb:
  device: 0
  log_steps: 1
  use_sage: False
  num_layers: 2
  hidden_channels: 256
  dropout: 0.5
  batch_size: 65535
  lr: 0.005
  epochs: 500
  eval_steps: 5
  runs: 10

plh:
  bool: True
  radius: 2
  degree: 8
  maxdim: 1
  resolution: 16
  center: False
  filtration: distance_matrix